config/routes.rb
Plusdollar::Application.routes.draw do
  

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  resources :orders

  get "home/index"

  root :to => 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable 
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable #, :registerable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :vendor, :admin
  validates :email, presence: true, format: { :with => /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/, :message => "must be a valid email address"}
  
  def admin?
    admin == true
  end
  
  def vendor?
    vendor == true
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user, html: {class: "form-horizontal"}) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :email, class: "control-label" %><br />
    <div class="controls">
    	<%= f.text_field :email %>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label :vendor, class: "control-label" %><br />
    <div class="controls">
    	<%= f.check_box :vendor %>
    </div>
  </div>
  
  <% if current_user.admin? %>
  	<div class="control-group">
    <%= f.label :admin, class: "control-label" %><br />
    <div class="controls">
    	<%= f.check_box :admin %>
    </div>
  </div>
  <% end %>
  
  <div class="actions">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<link rel="stylesheet" href="http://raw.github.com/cchike/cchike/master/app/assets/javascripts/TableSorter/themes/blue/style.css"> 
<script type="text/javascript" src="http://raw.github.com/cchike/cchike/master/app/assets/javascripts/TableSorter/jquery-latest.js"></script> 
<script type="text/javascript" src="http://raw.github.com/cchike/cchike/master/app/assets/javascripts/TableSorter/jquery.tablesorter.js"></script> 

<script>
	
	$(function() {
		$("#myTable2").tablesorter({theme:'blue',widgets:['zebra'],widthFixed:true});
	});

</script>

<table id="myTable2" class="tablesorter tablesorter-blue">
	<thead>
  <tr class="tablesorter-headerRow">
    <th>Email</th>
    <th>Vendor</th>
    <th>Admin</th>
    <th></th>
    <th></th>
  </tr>
  </thead>

	<tbody>
	<% @users.each do |user| %>
	  <tr>
	    <td><%= user.email %></td>
	    <td><%= user.vendor %></td>
	    <td><%= user.admin %></td>
	    <td><%= link_to 'Show', user %></td>
	    <td><%= link_to 'Edit', edit_user_path(user) %></td>
	  </tr>
	<% end %>
	</tbody>
</table>

<br />

<%= link_to 'New User', new_user_path, class: "btn btn-mini" %> <%= link_to 'View Orders', orders_path, class: "btn btn-mini"%> <%= link_to 'Return Home', root_path, class: "btn btn-mini" %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path, class: "btn btn-mini" %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>