config/routes.rb
Plusdollar::Application.routes.draw do
  

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  resources :orders

  get "home/index"

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Vago Logistics Orders</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    
 
	<!-- <script>
	$(document).ready(function(){
	  $("#help-button").click(function(){
	  	$("#help-button").fadeOut();
	    $("#help").fadeOut();
	  });
	});
	</script> -->
    
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <div class="nav-collapse collapse">
            <ul class="nav">
            	<% if current_user.admin? %>
              <li><%= link_to "Admin", rails_admin_path %></li>
              <% end %>
              <li><%= link_to "View Orders", orders_path %></li>
          <!--<li id="help">Select "Orders" to get started</li>
              <li><button id="help-button" type="button" class="btn-mini">Ok</button></li> -->
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

      <h1>Vago Logistics Orders</h1>
      

    </div> <!-- /container -->

  </body>
</html>